language: clojure
install: yes | sudo lein upgrade
script: lein with-profile +travis modules all
branches:
  only:
    - thedeuce
jdk:
  - openjdk7
  - oraclejdk7
notifications:
  email:
    - admin@immutant.org
